In [1]:
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, Normalizer, scale
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as  np

In [2]:
creditcard = pd.read_csv('cleanData.csv')
creditcard.columns = [x.lower() for x in creditcard.columns]
creditcard.rename(columns = {'class' : 'fraud'}, inplace = True)
creditcard

unnamed: 0      time         v1         v2        v3        v4  \
0                0       0.0  -1.359807  -0.072781  2.536347  1.378155   
1                1       0.0   1.191857   0.266151  0.166480  0.448154   
2                2       1.0  -1.358354  -1.340163  1.773209  0.379780   
3                3       1.0  -0.966272  -0.185226  1.792993 -0.863291   
4                4       2.0  -1.158233   0.877737  1.548718  0.403034   
5                5       2.0  -0.425966   0.960523  1.141109 -0.168252   
6                6       4.0   1.229658   0.141004  0.045371  1.202613   
7                7       7.0  -0.644269   1.417964  1.074380 -0.492199   
8                8       7.0  -0.894286   0.286157 -0.113192 -0.271526   
9                9       9.0  -0.338262   1.119593  1.044367 -0.222187   
10              10      10.0   1.449044  -1.176339  0.913860 -1.375667   
11              11      10.0   0.384978   0.616109 -0.874300 -0.094019   
12              12      10.0   1.249999  -1.221637  0.383930 -1.234899   
13              13      11.0   1.069374   0.287722  0.828613  2.712520   
14              14      12.0  -2.791855  -0.327771  1.641750  1.767473   
15              15      12.0  -0.752417   0.345485  2.057323 -1.468643   
16              16      12.0   1.103215  -0.040296  1.267332  1.289091   
17              17      13.0  -0.436905   0.918966  0.924591 -0.727219   
18              18      14.0  -5.401258  -5.450148  1.186305  1.736239   
19              19      15.0   1.492936  -1.029346  0.454795 -1.438026   
20              20      16.0   0.694885  -1.361819  1.029221  0.834159   
21              21      17.0   0.962496   0.328461 -0.171479  2.109204   
22              22      18.0   1.166616   0.502120 -0.067300  2.261569   
23              23      18.0   0.247491   0.277666  1.185471 -0.092603   
24              24      22.0  -1.946525  -0.044901 -0.405570 -1.013057   
25              25      22.0  -2.074295  -0.121482  1.322021  0.410008   
26              26      23.0   1.173285   0.353498  0.283905  1.133563   
27              27      23.0   1.322707  -0.174041  0.434555  0.576038   
28              28      23.0  -0.414289   0.905437  1.727453  1.473471   
29              29      23.0   1.059387  -0.175319  1.266130  1.186110   
...            ...       ...        ...        ...       ...       ...   
284777      284777  172764.0   2.079137  -0.028723 -1.343392  0.358000   
284778      284778  172764.0  -0.764523   0.588379 -0.907599 -0.418847   
284779      284779  172766.0   1.975178  -0.616244 -2.628295 -0.406246   
284780      284780  172766.0  -1.727503   1.108356  2.219561  1.148583   
284781      284781  172766.0  -1.139015  -0.155510  1.894478 -1.138957   
284782      284782  172767.0  -0.268061   2.540315 -1.400915  4.846661   
284783      284783  172768.0  -1.796092   1.929178 -2.828417 -1.689844   
284784      284784  172768.0  -0.669662   0.923769 -1.543167 -1.560729   
284785      284785  172768.0   0.032887   0.545338 -1.185844 -1.729828   
284786      284786  172768.0  -2.076175   2.142238 -2.522704 -1.888063   
284787      284787  172769.0  -1.029719  -1.110670 -0.636179 -0.840816   
284788      284788  172770.0   2.007418  -0.280235 -0.208113  0.335261   
284789      284789  172770.0  -0.446951   1.302212 -0.168583  0.981577   
284790      284790  172771.0  -0.515513   0.971950 -1.014580 -0.677037   
284791      284791  172774.0  -0.863506   0.874701  0.420358 -0.530365   
284792      284792  172774.0  -0.724123   1.485216 -1.132218 -0.607190   
284793      284793  172775.0   1.971002  -0.699067 -1.697541 -0.617643   
284794      284794  172777.0  -1.266580  -0.400461  0.956221 -0.723919   
284795      284795  172778.0 -12.516732  10.187818 -8.476671 -2.510473   
284796      284796  172780.0   1.884849  -0.143540 -0.999943  1.506772   
284797      284797  172782.0  -0.241923   0.712247  0.399806 -0.463406   
284798      284798  172782.0   0.219529   0.881246 -0.635891  0.960928   
284799      

In [3]:
creditcard.fraud.value_counts(dropna = False)

0    284315
1       492
Name: fraud, dtype: int64

In [4]:
creditcard.groupby('fraud').amount.mean()

fraud
0     88.291022
1    122.211321
Name: amount, dtype: float64

In [5]:
creditcard.drop('time' , axis = 1, inplace = True)

In [6]:
scaler = StandardScaler()
creditcard['amount'] = scaler.fit_transform(creditcard['amount'].values.reshape(-1,1))

In [9]:
X = creditcard.iloc[:,:-1]
y = creditcard.iloc[:, -1]
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, y, test_size = .33, stratify = y, random_state = 1)

In [10]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth = 6, random_state=0)
clf.fit(Xtrain, Ytrain)
clf.score(Xtrain,Ytrain),clf.score(Xtest,Ytest)

(0.99977989728539984, 0.99970208645876557)

In [11]:
y_train_pred = clf.predict(Xtrain)
y_test_pred = clf.predict(Xtest)

In [12]:
from sklearn.metrics import confusion_matrix

In [13]:
confusion_matrix(ytrain, y_train_pred)

array([[   290,     40],
       [     2, 190488]], dtype=int64)

In [14]:
confusion_matrix(ytest, y_test_pred)

array([[  138,    24],
       [    4, 93821]], dtype=int64)

In [15]:
from sklearn.metrics import classification_report
from  sklearn.metrics import precision_recall_fscore_support


def pandas_classification_report(y_true, y_pred):
    metrics_summary = precision_recall_fscore_support(
            y_true=y_true, 
            y_pred=y_pred)

    avg = list(precision_recall_fscore_support(
            y_true=y_true, 
            y_pred=y_pred,
            average='weighted'))

    metrics_sum_index = ['precision', 'recall', 'f1-score', 'support']
    class_report_df = pd.DataFrame(
        list(metrics_summary),
        index=metrics_sum_index)

    support = class_report_df.loc['support']
    total = support.sum() 
    avg[-1] = total

    class_report_df['avg / total'] = avg

    return class_report_df.T

In [16]:
print(classification_report(y_true=ytest, y_pred=y_test_pred, digits=6))

             precision    recall  f1-score   support

        0.0   0.971831  0.851852  0.907895       162
        1.0   0.999744  0.999957  0.999851     93825

avg / total   0.999696  0.999702  0.999692     93987



In [17]:
clf.score(Xtest,ytest)

0.99970208645876557

In [18]:
clf.predict_proba(Xtest)

array([[  1.46725084e-04,   9.99853275e-01],
       [  1.50440976e-04,   9.99849559e-01],
       [  1.50440976e-04,   9.99849559e-01],
       ..., 
       [  1.17746401e-04,   9.99882254e-01],
       [  1.32130089e-04,   9.99867870e-01],
       [  1.32130089e-04,   9.99867870e-01]])

In [19]:
df_class_report = pandas_classification_report(y_true=ytest, y_pred=y_test_pred)
print(df_class_report)
df_class_report.to_csv('classDT.csv',  sep=',')

             precision    recall  f1-score  support
0             0.971831  0.851852  0.907895    162.0
1             0.999744  0.999957  0.999851  93825.0
avg / total   0.999696  0.999702  0.999692  93987.0


In [20]:
df = pd.DataFrame({'Class':y_test_pred, 'Feature' : Xtest['amount'] })
df.head()

Class   Feature
206218    1.0 -0.317726
21380     1.0 -0.081360
145812    1.0 -0.326202
164815    1.0 -0.325283
268205    1.0 -0.350071

In [21]:
df.to_csv("Predict_RF.csv")